spring:
  datasource:
    url: jdbc:mysql://localhost:3307/cars?createDatabaseIfNotExist=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: toor
  jpa:
    hibernate:
      ddl-auto: update
