version: "3.8"


services:
  mysql-db:
    container_name: mysql_db_batch
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_PASSWORD: toor
    ports:
      - "3307:3306"
    expose:
      - 3307:3306